fail_on_violations: true

rubocop:
  config_file: .rubocop.yml

reek:
  enabled: true
  config_file: .reek.yml

coffeescript:
  enabled: false

jshint:
  enabled: false

scss:
  enabled: false

eslint:
  enabled: true
  config_file: .eslintrc
  ignore_file: .eslintignore
